- rule: TOCTOU ConfigMap Modification Detected
  desc: Detects attempted modification of files in a mounted ConfigMap (TOCTOU pattern).
  condition: >
    (evt.type in (open, openat, openat2) and
     evt.is_open_write = true) and
     fd.name startswith "/mnt/configmap" and
    container
  output: >
    TOCTOU ConfigMap modification attempt detected by %proc.name (user=%user.name, container=%container.id)
    opening file %fd.name
  priority: WARNING
  tags: [k8s, configmap, toctou, runtime]