apiVersion: v1
kind: ServiceAccount
metadata:
  name: rbac-abuser
  namespace: default

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: rbac-abuse
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rbac-abuse-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: rbac-abuser
    namespace: default
roleRef:
  kind: Role
  name: rbac-abuse
  apiGroup: rbac.authorization.k8s.io